name: DevOps Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Pull UBI9 Python 3.12 image
      run: docker pull registry.access.redhat.com/ubi9/python-312

    - name: Run Python print inside container
      run: docker run --rm registry.access.redhat.com/ubi9/python-312 python3 -c 'print("Hello world")'

    - name: List Docker images on agent
      run: docker images
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run workflow listing script
      run: python3 script.py
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
